# Generated by Django 4.1.5 on 2023-01-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
